language: node_js
node_js:
  - '0.10.29'

deploy:
  provider: s3
  access_key_id: AKIAJ2IV65GOPVWTN3LA
  secret_access_key:
    secure: W+BO9/+xrlXrQrA5cqlmwQ49g6wJD0lvugpTyDHUIUB/X0b8Jvch5xuV6oi9xsqeBHnnHmqmocuF0hCncK2MLIPtRAqVhn6oMzMAd2Rux7y2ZsChhtqzbWF2guXTkZ15ZYSV9EKrkZC7pcUbUnVoWweCAlZtDnQsVMsBVLRXHjQ=
  bucket: livesnooker
  local-dir: build
  skip_cleanup: true
  region: eu-west-1
